import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Components/Navbar";
import {  Lato as PlayFont  } from "next/font/google";
import { Footer } from "./Components/footer";
import { products } from "@/public/frontend_assets/assets";
import {  ShopContextProvider } from "./context/ShopContext";
import Layout from "./(root)/layout";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playFont = PlayFont({
  style : ["normal"],
  subsets : ["latin"],
  weight:"400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playFont.className} ${geistSans.className} px-4 sm:px-[5vw] md:px-[7vw] lg:px-[9vw]  `}>
       <main>
        <ShopContextProvider>

          {children}

        </ShopContextProvider>

        
        </main>
      </body>
    </html>
  );
}
